### ISSUE TITLE
Not ignoring commented out files in the yaml config

### ISSUE THREAD

**Issue by stealthv** [dcwatson/dpack#1]
If you comment out a file in the yaml config it still gets included when the files are packed together. It should be ignored.

**Comment by stealthv** [comment]
example, jQuery is commented out but will still be included in `all_the_things.js`:
```yaml
assets:
  compiled/js/all_the_things.js:
    # - js/jquery-3.3.1.min.js
    - js/my_stuff.js
output: ./build
```
